version: "3"
services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - patstat-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - patstat-network
    depends_on:
      - redis

  worker:
    build: .
    privileged: true
    command: >
        /bin/sh -c "python3 manage.py run_worker"
    environment:
      APP_SETTINGS: application.server.config.DevelopmentConfig
      MOUNTED_VOLUME_TEST: '/volume_test/'
      MOUNTED_VOLUME_TEST_FALL2021: '/volume_test_fall2021/'
      MOUNTED_VOLUM_INPI_PATH: '/volume_inpi_path/'
      MOUNTED_VOLUM_INPI_DATA: '/volume_inpi_data/'
    volumes:
      - /run/media/julia/DATA/test/:/volume_test
      - /run/media/julia/DATA/test/2021_Autumn/:/volume_test_fall2021
      - /run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/:/volume_inpi_path
      - /run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017_2020/2021/:/volume_inpi_data
    networks:
      - patstat-network
    depends_on:
      - redis

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3 /src/manage.py run -h 0.0.0.0
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: application.server.config.DevelopmentConfig
      MOUNTED_VOLUME_TEST: '/volume_test/'
      MOUNTED_VOLUME_TEST_FALL2021: '/volume_test_fall2021/'
      MOUNTED_VOLUM_INPI_PATH: '/volume_inpi_path/'
    volumes:
      - /run/media/julia/DATA/test/:/volume_test
      - /run/media/julia/DATA/test/2021_Autumn/:/volume_test_fall2021
      - /run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/:/volume_inpi_path
    networks:
      - patstat-network
    depends_on:
      - worker

networks:
  patstat-network:
    driver: bridge

volumes:
  volume_test:
  volume_test_fall2021:
  volume_inpi_path:
