version: "3"

services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - patstat-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - patstat-network
    depends_on:
      - redis

  worker:
    build: .
    privileged: true
    command: >
        /bin/sh -c "python3 /home/julia/Documents/harvest-patstat/manage.py run_worker"
    environment:
      APP_SETTINGS: application.server.config.DevelopmentConfig
      LOCAL: "/home/julia/Documents/harvest-patstat/"
      MOUNTED_VOLUME_TEST: '/run/media/julia/DATA/test/'
      MOUNTED_VOLUME_FALL2021: "/run/media/julia/DATA/test/2021_Autumn/"
      MOUNTED_VOLUM_INPI_PATH: "/run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017-2020/2020"
    networks:
      - patstat-network
    depends_on:
      - redis
    volumes:
      - /home/julia/Documents/harvest-patstat/:/home/julia/Documents/harvest-patstat/
      - /run/media/julia/DATA/test:/run/media/julia/DATA/test
      - /run/media/julia/DATA/test/2021_Autumn/:/run/media/julia/DATA/test/2021_Autumn/
      - /run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017-2020/2020:/run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017-2020/2020
      
      

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3 /home/julia/Documents/harvest-patstat/manage.py run -h 0.0.0.0
    environment:
      LOCAL: "/home/julia/Documents/harvest-patstat/"
      MOUNTED_VOLUME_TEST: '/run/media/julia/DATA/test/'
      MOUNTED_VOLUME_FALL2021: "/run/media/julia/DATA/test/2021_Autumn/"
      MOUNTED_VOLUM_INPI_PATH: "/run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017-2020/2020"
      FLASK_DEBUG: 1
      APP_SETTINGS: application.server.config.DevelopmentConfig
    networks:
      - patstat-network
    depends_on:
      - worker
    volumes:
      - /home/julia/Documents/harvest-patstat/:/home/julia/Documents/harvest-patstat/
      - /run/media/julia/DATA/test:/run/media/julia/DATA/test
      - /run/media/julia/DATA/test/2021_Autumn/:/run/media/julia/DATA/test/2021_Autumn/
      - /run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017-2020/2020:/run/media/julia/DATA/DONNEES/PATENTS/SOURCES/INPI/2017-2020/2020

networks:
  patstat-network:
    driver: bridge

