version: "3"
services:
  redis:
    image: redis:5.0.7-alpine
    networks:
      - patstat-network

  dashboard:
    image: dataesr/dashboard-crawler:1.1
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    networks:
      - patstat-network
    depends_on:
      - redis

  worker:
    build: .
    privileged: true
    command: >
        /bin/sh -c "python3 manage.py run_worker"
    environment:
      APP_SETTINGS: application.server.config.DevelopmentConfig
      MOUNTED_VOLUME: '/patstat_data/'
    volumes:
      - /Users/eric/:/patstat_data
    networks:
      - patstat-network
    depends_on:
      - redis

  web:
    build: .
    privileged: true
    ports:
      - 5004:5000
    command: python3 /src/manage.py run -h 0.0.0.0
    environment:
      FLASK_DEBUG: 1
      APP_SETTINGS: application.server.config.DevelopmentConfig
      MOUNTED_VOLUME: '/patstat_data/'
    volumes:
      - /Users/eric/:/patstat_data
    networks:
      - patstat-network
    depends_on:
      - worker

networks:
  patstat-network:
    driver: bridge

volumes:
  patstat_data:
