name: Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dataesr/harvest-patstat
  DEPLOYMENT_URL: https://github.com/dataesr/harvest-patstat/pkgs/container/harvest-patstat
  MM_NOTIFICATION_CHANNEL: bots

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v4

      - name: 🐋 Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: 🔑 Login Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  notify:
    needs: build-and-push-ghcr
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1.0.2
        with:
          deployment_url: ${{ env.DEPLOYMENT_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mattermost_channel: ${{ env.MM_NOTIFICATION_CHANNEL}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}